namespace SpecflowPlaywrightPOC.Pages.Quotepage
{
    public partial class QuotePage
    {
        public const string MenuHome = "ctl00_ctl00_CPHPageBaseContent_CPHPageHeaderContent_CPHPageHeaderMainMenu_MMainNavigationn0";
        public const string MenuSearch = "ctl00_ctl00_CPHPageBaseContent_CPHPageHeaderContent_CPHPageHeaderMainMenu_MMainNavigationn1";
        public const string MenuNewOffer = "ctl00_ctl00_CPHPageBaseContent_CPHPageHeaderContent_CPHPageHeaderMainMenu_MMainNavigationn2";
        public const string MenuNewsList = "ctl00_ctl00_CPHPageBaseContent_CPHPageHeaderContent_CPHPageHeaderMainMenu_MMainNavigationn3";
        public const string MenuHelp = "ctl00_ctl00_CPHPageBaseContent_CPHPageHeaderContent_CPHPageHeaderMainMenu_MMainNavigationn4";
        public const string MenuSimulation = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_MQuotationDetailsn0";
        public const string MenuProposalSimulation = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_MProposalDetailsn0";
        public const string MenuOtherData = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_MProposalDetailsn2";
        public const string MenuEntities = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_MProposalDetails_ctl01_lblMenuItem";
        public const string MenuBankInformation = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_MOwnGeneralDetailsn2";
        public const string MenuAdditionalInfo = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_MOwnDetailsn1";
        public const string MenuEmploymentHistory = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_MHouseholdDetails_ctl00_lblMenuItem";
        public const string MenuConsent = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_MHouseholdDetails_ctl01_lblMenuItem";
        public const string TextOccupationNotes = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBProfessionDescr";
        public const string EmploymentStartDateMonth = "//input[@id='ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBLabourAgreementBeginMonth']";
        public const string EmploymentStartDateYear = "//input[@id='ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBLabourAgreementBeginYear']";
        public const string TextYearWithEmployer = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBLabourSeniority";
        public const string TextHouseNumber = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBHouseNumber";
        public const string TextBuildingName = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBBuilding";
        public const string InputFieldCounty = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_DDLDistrictCode";
        public const string MenuBusinessInterest = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_MHouseholdDetails_ctl02_lblMenuItem";
        public const string InputCompanyCheckBoxAsYes = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_FVPersonBorrowerUnit_DDLBUMajorParticipation";
        public const string ButtonPlusToAddCompanyData = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocGrid_GVOtherLegalDoc_ctl01_IBInsert";
        public const string EntityType = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_DDLEntityTypeId";
        public const string JuridicalType = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_DDLJuridicalTypeId";
        public const string TextCompanyName = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBFullName";
        public const string TextCompanyNumber = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBLegalDocNumber";
        public const string TextPostCodeOnBusinessInterestTab = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBPostalCodeSearch";
        public const string TextStreetOnBusinessInterestTab = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBStreet";
        public const string TextHouseNumberOnBusinessInterestTab = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBHouseNumber";
        public const string TextApartmentOnBusinessInterestTab = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBApartment";
        public const string TextBuildingOnBusinessInterestTab = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBBuilding";
        public const string TextLocalityOnBusinessInterestTab = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBLocality";
        public const string InputCounty = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_DDLDistrictCode";
        public const string TextValidFromDateOnBusinessInterestTab = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocForm_FVOtherLegalDocForm_TBAddressInUseSince";
        public const string BusinessInterestConfirmButton = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCPersonBorrowerUnit_UCOtherLegalDoc_UCOtherLegalDocGrid_GVOtherLegalDoc_ctl02_IBConfirm";
        public const string InputKind = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOperSearch_CPHMain_FVCredOperSearch_DDLCredOperStep";
        public const string InputProductType = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_FVSimulation_DDLAplBusinessId";
        public const string InputVehicleClass = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCAssetVehicle_FVAssetAuto_DDLEquipmentCategoryId";
        public const string InputVehicleState = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCAssetVehicle_FVAssetAuto_DDLEquipmentStateId";
        public const string InputMake = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCAssetVehicle_FVAssetAuto_DDLEquipmentBrand";
        public const string InputModel = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCAssetVehicle_FVAssetAuto_DDLEquipmentModel";
        public const string InputVersion = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCAssetVehicle_FVAssetAuto_DDLEquipmentVersion";
        public const string InputProductVariant = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCFinancialProduct_FVFinancialProduct_DDLFinancialProductId";
        public const string InputPaymentMethod = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCFinancing_FVFinancing_DDLInitialEntryPaymentBehaviourTypeId";
        public const string InputStateTransition = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_DDLTransitionId";
        public const string ButtonNewEmpHistory = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentGrid_GVEmployment_ctl01_IBInsert";
        public const string TextEntityGeneralTabFirstName = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_FVOwnGeneral_TBFirstName";
        public const string TextEntityGeneralTabLastName = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_FVOwnGeneral_TBLastName";
        public const string TextEntityGeneralTabDateOfBirth = "//input[@id='ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_FVOwnGeneral_TBBirthDate']";
        public const string InputEntityGender = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_FVOwnGeneral_DDLGenderId";
        public const string InputJuridicalType = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_FVIntervEntity_DDLJuridicalTypeId";
        public const string InputTitle = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_FVOwnGeneral_DDLTitleId";
        public const string InputGender = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_FVOwnGeneral_DDLGenderId";
        public const string InputAdressCountry = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnAddress_UCOwnAddressForm_FVAddress_DDLDistrictCode";
        public const string InputMaritalStatus = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_FVHousehold_DDLMaritalStatusId";
        public const string InputResidenceType = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_FVHousehold_DDLResidenceTypeId";
        public const string InputOccupation = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_DDLProfessionId";
        public const string InputEmploymentStatus = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_DDLLabourAgreementTypeId";
        public const string InputDistricCode = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_DDLDistrictCode";
        public const string InputQuestionAnswer = "CustomSelectContainer_ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCFormResponse_CPHMain_FVFormResponse_RQuestions_ctl05_DDLQuestionAnswerId";
        public const string ButtonNewforPrivateContact = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnPrivateContact_UCOwnPhoneGrid_GVOwnPhone_ctl01_IBInsert";
        public const string TextPrivatePhoneNumber = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnPrivateContact_UCOwnPhoneGrid_GVOwnPhone_ctl02_TBPhoneNumber";
        public const string PrivateContactConfirmButton = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnPrivateContact_UCOwnPhoneGrid_GVOwnPhone_ctl02_IBConfirm";
        public const string TextPrivateEmailAddress = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnPrivateContact_FVOwnPrivateContact_TBEmailAddress";
        public const string ButtonVehicleSheetClose = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCAssetVehicle_FVAssetAuto_IBCloseBOXAssetSheet";
        public const string ButtonCalculate = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCFinancialProduct_FVFinancialProduct_IBCalculator";
        public const string ButtonResultsClose = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCResults_IBClose";
        public const string ButtonSavePosQuote = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_IBSave";
        public const string ButtonAckCheckBox = "//input[@id='ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_FVOwnGeneral_CBConsentUseData']";
        public const string ButtonInsertEntity = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityGrid_GVIntervEntity_ctl01_IBInsert";
        public const string ButtonInsertAddress = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnAddress_UCOwnAddressGrid_GVOwnAddress_ctl01_IBInsert";
        public const string ButtonDeclareCheckBox = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_FVOwnGeneral_CBValidationRequiredByUser";
        public const string ButtonAddressConfirm = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnAddress_UCOwnAddressGrid_GVOwnAddress_ctl02_IBConfirm";
        public const string ButtonInsertPhoneNumber = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnPrivateContact_UCOwnPhoneGrid_GVOwnPhone_ctl01_IBInsert";
        public const string ButtonPhoneConfirm = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnPrivateContact_UCOwnPhoneGrid_GVOwnPhone_ctl02_IBConfirm";
        public const string ButtonAccountConfirm = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCBankInfo_FVBankInfo_IBValidateBankInfo";
        public const string ButtonInsertEmployment = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentGrid_GVEmployment_ctl01_IBInsert";
        public const string ButtonEmploymentConfirm = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentGrid_GVEmployment_ctl02_IBConfirm";
        public const string ButtonEntityConfirm = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityGrid_GVIntervEntity_ctl02_IBConfirm";
        public const string LabelPosQuoteID = "//div[@class='ContainerHeaderTitle ellipsis']";
        public const string ProposalTitile = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_LTitle";
        public const string TextOrderDate = "//*[@id='ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCAssetVehicle_FVAssetAuto_TBClientSignatureDate']";
        public const string TextfieldColour = "//span[contains(text(),'Colour')]/following-sibling::div/input";
        public const string TextEntityFirstName = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_FVIntervEntity_TBFirstName";
        public const string TextEntitySurName = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_FVIntervEntity_TBLastName";
        public const string TextEntityDob = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_FVIntervEntity_TBBirthDate";
        public const string TextEntityPostCode = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_FVIntervEntity_TBPostalCode";
        public const string TextAddressStreet = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnAddress_UCOwnAddressForm_FVAddress_TBStreet";
        public const string TextAdressPostcode = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnAddress_UCOwnAddressForm_FVAddress_TBPostalCode";
        public const string TextAdressValidFrom = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnAddress_UCOwnAddressForm_FVAddress_TBAddressInUseSince";
        public const string TextPhoneNumber = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnPrivateContact_UCOwnPhoneGrid_GVOwnPhone_ctl02_TBPhoneNumber";
        public const string TextEmailId = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCOwnPrivateContact_FVOwnPrivateContact_TBEmailAddress";
        public const string TextAccountNumber = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCBankInfo_FVBankInfo_TBAccountNumber";
        public const string TextSortCode = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCBankInfo_FVBankInfo_TBOfficialCode";
        public const string TextTimeWithBankYear = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCBankInfo_FVBankInfo_TBAccountSeniorityYear";
        public const string TextTimeWithBankMonth = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCOwnGeneral_UCBankInfo_FVBankInfo_TBAccountSeniorityMonth";
        public const string TextMonthlyRentalPayment = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_FVHousehold_TBResidenceDuties";
        public const string TextEmployerName = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBEmploymentCompany";
        public const string TextContractBegin = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBLabourAgreementBeginDate";
        public const string TextEmpAddressStreet = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBStreet";
        public const string TextEmpAddressPostCode = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBPostalCode";
        public const string TextEmpAddressPhoneNo = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBPhoneNumber";
        public const string TextEmpAddressValidfrom = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCIntervEntities_UCIntervEntityForm_UCOwn_UCHousehold_UCEmploymentEntity_UCEmploymentForm_FVEmployment_TBAddressInUseSince";
        public const string TextPosProposalID = "LTBCredOperNumber";
        public const string TextPosProposalState = "LDDLAutUserStateId";
        public const string TextPosQuoteID = "LTBCredOperOrigin";
        public const string ButtonOk = "//input[@value='OK']";
        public static string Menu(string label) => $"//div[@class='MainNavigation']//a[text()='{label}']";
        public static string DropDownbox(string label) => $"//span[text()='{label}']/following-sibling::div/div";
        public static string SelectedOption(string option) => $"//ul[@class='CustomSelect']/li[text()='{option}']";
        public static string TextField(string label) => $"//span[contains(text(),'{label}')]/following-sibling::div/input";
        public static string TextBox(string label) => $"//span[text()='{label}']/following-sibling::span[1]";
        public static string AlternativeDropDownbox(string label) => $"//a[text()='{label}']/following-sibling::div";
        public static string Button(string label) => $"//div[@title='{label}']/input";
        public static string Tab(string label) => $"//span[text()='{label}']/ancestor::a";
        public static string CheckBox(string label) => $"//span[text()='{label}']/../div//input";
        public static string PostCode(string label) => $"//legend[text()='{label}']/..//span[contains(text(),'Post Code')]/following-sibling::div/input";
        public static string ClosePanel(string label) => $"//span[text()='{label}']/following-sibling::div/input";
        public const string ButtonStateTransition = "//input[@Title='Do Transition']";
        public const string AddNewRecord = "//div[text()='No records found.']/following-sibling::div/input";
        public const string AddNewPhone = "//div[text()='There are no phones.']/following-sibling::div/input";
        public const string TextRentalsInAdvance = "ctl00_ctl00_CPHPageBaseContent_CPHMainContent_UCCredOper_CPHMain_UCSimulation_UCFinancing_FVFinancing_TBInitialEntryFactor";
    }
}